### PR TITLE
131 authentication backend

### PR DESCRIPTION
**Pull request by Akongstad**

### CODE REVIEW

**Comment by Akongstad** [comment]
Quality gate fails because sonar cloud is not yet on main I think. Requires coverage >80, but is 0 because not on main

**Comment by Stribe02** [comment]
It seems like it fails because SonarCloud does not like that we have outcommented code and an unused local variable..? The two "major" issues for SonarCloud is the outcommented code that has not been removed

**Comment by Akongstad** [comment]
I can confirm that it did fail before commented it out. It is because the default quality gate requires 80 % coverage

**Comment by Stribe02** [comment]
Ah fair, only looked at the Code smells listed and not the coverage stuff.. I will approve the pull request then

**Review by Stribe02 — APPROVED** [review]

**Review by Stribe02 — APPROVED** [review]

**Review by mikaeleythor — APPROVED** [review]

**Pull request merged**
